import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import SessionWrapper from "@/components/SessionWrapper";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/Navbar";
import { VideoPlayerProvider } from '../context/VideoPlayerContext';
import React from 'react';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "YouEducation",
  description: "Generated by R&R",
  icons: {
    icon: [
      { url: '/static/images/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/static/images/favicon-32x32.png', sizes: '32x32', type: 'image/png' }
    ],
    apple: { url: '/static/images/apple-touch-icon.png', sizes: '180x180', type: 'image/png' },
    shortcut: '/static/images/favicon-32x32.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <SessionWrapper>
        <body className={`min-h-screen flex flex-col bg-white dark:bg-gray-950 ${geistSans.variable} ${geistMono.variable}`}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <Navbar />
            <VideoPlayerProvider>
              <main className="flex-grow">
                {children}
              </main>
            </VideoPlayerProvider>
          </ThemeProvider>
          <Toaster />
        </body>
      </SessionWrapper>
    </html>
  );
}