import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import SessionWrapper from "@/components/SessionWrapper";
import { Toaster } from "@/components/ui/sonner"
import Navbar from "@/components/Navbar";
import { VideoPlayerProvider } from '../context/VideoPlayerContext';
import React from 'react';
import { Footer } from '@/components/Footer';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "YouEducation",
  description: "Generated by R&R",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <SessionWrapper>
      <body className="min-h-screen flex flex-col bg-white dark:bg-gray-950">
        
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Navbar />
          <VideoPlayerProvider>
            <main className="flex-grow">
              {children}
            </main>
          </VideoPlayerProvider>
        </ThemeProvider>
        <Footer />
        <Toaster />
      </body>
      </SessionWrapper>
    </html>
  );
}
